steps:
- name: 'node'
  entrypoint: 'yarn'
  args:
  - install

- name: 'node'
  entrypoint: 'yarn'
  args:
  - build

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - createReservation
  - --region=europe-west1
  - --memory=1024
  - --source=.
  - --trigger-http
